language: python
python:
  - 2.7
  - 3.4
  - 3.5
#  - 3.5-dev
#  - nightly
#  - pypy
#  - pypy3
env:
  matrix:
    - SUITE=nose EXTRAS=""
    - SUITE=nose EXTRAS="[pint]"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install -e ".${EXTRAS}"
script:
  - make "$SUITE"
after_success:
  - coveralls
matrix:
  include:
    - python: 3.5
      env: SUITE=html EXTRAS="[pint]"
    - python: 3.5
      env: SUITE=doctest EXTRAS="[pint]"
    - python: 3.5
      env: SUITE=hardcases-stability EXTRAS="[pint]"
