language: python
python:
  - "pypy"
  - "pypy3"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
env:
  - EXTRAS=""
  - EXTRAS="[pint]"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install -e ".${EXTRAS}"
script:
  - nosetests --with-coverage --cover-package=bytesize
  - cd docs && make doctest
  - cd docs && make html
after_success:
  - coveralls
