language: python
python:
  - 2.7
  - 3.4
  - 3.5
#  - 3.5-dev
#  - nightly
#  - pypy
#  - pypy3
env:
  global:
    - SPHINX=false
  matrix:
    - EXTRAS=""
    - EXTRAS="[pint]"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install -e ".${EXTRAS}"
script:
  - nosetests --with-coverage --cover-package=bytesize
  - (if [[ "$SPHINX" = true ]]; then cd docs && make doctest; else true; fi)
  - (if [[ "$SPHINX" = true ]]; then cd docs && make html; else true; fi)
after_success:
  - coveralls
matrix:
  include:
    - python: "2.7"
      env: SPHINX=true
    - python: "3.4"
      env: SPHINX=true
