language: python
python:
  - 2.7
  - 3.4
  - 3.5
#  - 3.5-dev
#  - nightly
#  - pypy
#  - pypy3

env:
  matrix:
    - SUITE=test EXTRAS=""
    - SUITE=test EXTRAS="[pint]"
    - SUITE=html EXTRAS="[pint]"
    - SUITE=doctest EXTRAS="[pint]"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install -e ".${EXTRAS}"

script:
  - make "$SUITE"

after_success:
  - coveralls

matrix:
  exclude:
    - python: 2.7
      env: SUITE=html EXTRAS="[pint]"
    - python: 2.7
      env: SUITE=doctest EXTRAS="[pint]"
